PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
    command: ['bundle', 'exec', 'rubocop']
  Brakeman:
    enabled: true
    on_warn: fail
    command: ['bundle', 'exec', 'brakeman']

PrePush:
  BundlerAudit:
    enabled: true
    on_warn: fail
    command: ['bundle', 'exec', 'bundle', 'audit', '--update']
